name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Repository
        run: |
          pwd
          ls -la

      - name: Verify Docker
        run: |
          docker --version
          docker info

      - name: Build Docker Image
        run: |
          docker build \
            -t go-e2e:${{ github.sha }} \
            .

      - name: List Docker Images
        run: docker images

      - name: Inspect Docker Image
        run: docker image inspect go-e2e:${{ github.sha }}